image: continuumio/miniconda3


testing:
  stage: test
  script:
    - apt update && apt install -y  gcc && apt-get clean
    - conda env create -f Docker/conda_environments/assembly.yml
    - conda env create -f Docker/conda_environments/kat.yml && conda clean -a
    - conda env create -f Docker/conda_environments/confindr.yml && conda clean -a
    - conda env create -f Docker/conda_environments/quast.yml && conda clean -a
    - pip install -r Docker/requirements.txt
    - cp Docker/scripts/filter_contigs.py /usr/local/bin/
    - export PATH=/opt/conda/bin:/opt/conda/condabin:/opt/conda/envs/assembly/bin:/opt/conda/envs/quast/bin:/opt/conda/envs/confindr/bin:/opt/conda/envs/kat/bin:$PATH
    - echo $PATH
    - bwa -h



  
