image: docker:19.03.0-dind
variables:
  DEBIAN_FRONTEND: noninteractive
  NXF_ANSI_LOG: 'false'

stages:
  - test

testing:
  stage: test
  script:
    - apt update && apt install -qq -y wget openjdk-11-jdk bash && apt-get clean
    - |
      wget -qO- get.nextflow.io | bash
      mv nextflow /usr/local/bin/
    - >
      nextflow run main.nf
      --input_dir small_test_input
      --output_dir test_output
      --fastq_pattern "*{R,_}{1,2}.fastq.gz"
      --adapter_file adapters.fas
      --qc_conditions qc_conditions_nextera.yml
      --full_output
      --cutadapt
      -profile test

