image: ubuntu:20.04
variables:
  DEBIAN_FRONTEND: noninteractive

stages:
  - test

testing:
  stage: test
  script:
    - apt update && apt install -y wget openjdk-11-jdk apt-transport-https ca-certificates curl software-properties-common && apt-get clean
    - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
    - add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable"
    - apt update && apt-cache policy docker-ce && apt install -y docker-ce
    - service docker start
    - useradd -m -s /usr/bin/bash nf_user && usermod -aG docker nf_user
    - su - nf_user -c "wget -qO- get.nextflow.io | bash"
    - >
      su - nf_user -c "NXF_ANSI_LOG=false ./nextflow run $PWD/main.nf
      --input_dir $PWD/small_test_input
      --output_dir $PWD/test_output
      --fastq_pattern '*{R,_}{1,2}.fastq.gz'
      --adapter_file $PWD/adapters.fas
      --qc_conditions $PWD/qc_conditions_nextera.yml
      --full_output
      --cutadapt
      -profile test"

