image: docker:19.03.12-dind
variables:
  DEBIAN_FRONTEND: noninteractive

stages:
  - test

testing:
  stage: test
  script:
    - apk update && apk add openjdk11 wget bash
    - touch hello.txt
    - ls -la
    - docker run --privileged -w $PWD -v $PWD:$PWD quay.io/nextflow/bash bash -c 'ls -la'

