image: ubuntu:20.04
variables:
  DEBIAN_FRONTEND: noninteractive
  NXF_ANSI_LOG: 'false'

stages:
  - test

testing:
  stage: test
  script:
    - |
      apt update &&
      apt install -y wget openjdk-11-jdk apt-transport-https ca-certificates curl software-properties-common &&
      apt-get clean
    - add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable"
    - apt update && apt-cache policy docker-ce && apt install docker-ce
    - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -

    - |
      wget -qO- get.nextflow.io | bash
      mv nextflow /usr/local/bin/
    - 
    - >
      nextflow run main.nf
      --input_dir small_test_input
      --output_dir test_output
      --fastq_pattern "*{R,_}{1,2}.fastq.gz"
      --adapter_file adapters.fas
      --qc_conditions qc_conditions_nextera.yml
      --full_output
      --cutadapt
      -profile test
