image: docker:latest
services:
  - docker:dind
variables:
  SHARED_PATH: /builds/shared/$CI_PROJECT_PATH

testing:
  stage: test
  script:
    - mkdir -p ${SHARED_PATH}
    - touch ${SHARED_PATH}/test_file
    - docker run -v ${SHARED_PATH}:/mnt ubuntu ls /mnt



  
