image: ubuntu:20.04
variables:
  DEBIAN_FRONTEND: noninteractive

stages:
  - test

testing:
  stage: test
  script:
    - apt update && apt install -y wget openjdk-11-jdk docker.io && apt-get clean
    - docker --version
    -  |
      wget -qO- get.nextflow.io | bash
      mv nextflow /usr/local/bin/
    - nextflow -version
