image: ubuntu:20.04

stages:
  - test

testing:
  stage: test
  script:
    - apt update && apt install -y wget openjdk-11-jdk docker.io && apt-get clean
    - docker --version
    -  |
      wget -qO- get.nextflow.io | bash
      sudo mv nextflow /usr/local/bin/
    - nextflow help
