image: docker:latest
services:
  - docker:dind
variables:
  SHARED_PATH: /builds/shared/$CI_PROJECT_PATH

testing:
  stage: test
  script:
    - echo $PWD
    - ls -la
    - touch test.txt
    - docker run -w $PWD -v $PWD:$PWD quay.io/nextflow/bash bash -c 'ls -la'



  
