image: docker:19.03.12-dind


testing:
  stage: test
  script:
    - echo $PWD
    - ls -la
    - mkdir /data
    - chown +r /data
    - touch /data/test.txt
    - docker run --privileged -w $PWD -v /data:/data quay.io/nextflow/bash bash -c 'ls -la /data'



  
