image: docker:19.03.12-dind
variables:
  DEBIAN_FRONTEND: noninteractive

stages:
  - test

testing:
  stage: test
  script:
    - echo $PWD
    - nkdir /data
    - touch /data/hello.txt
    - docker run --privileged -w $PWD -v /data:/data quay.io/nextflow/bash bash -c 'ls -la /data'
    

