image: docker:19.03.12-dind
variables:
  DEBIAN_FRONTEND: noninteractive

stages:
  - test

testing:
  stage: test
  script:
    - echo $PWD
    - touch $PWD/hello.txt
    - mkdir /builds/$CI_PROJECT_PATH/shared
    - cp -r $PWD /builds/$CI_PROJECT_PATH/shared
    - ls -la /builds/$CI_PROJECT_PATH/shared
    - docker run --privileged -w $PWD -v /builds/$CI_PROJECT_PATH/shared:/data quay.io/nextflow/bash bash -c 'ls -la /data'
    

